# Generated by Django 4.1 on 2022-10-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoBlogAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
