# Generated by Django 4.1 on 2022-10-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBlog', models.IntegerField()),
                ('titulo', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(max_length=60)),
                ('contenido', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellidoPaterno', models.CharField(max_length=60)),
                ('apellidoMaterno', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('tipoUsuario', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
