# Generated by Django 4.1 on 2022-10-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnoBlog', '0002_delete_usuarios'),
        ('tecnoBlog', '0003_avatar'),
    ]

    operations = [
    ]
